### ISSUE TITLE
Wii Nunchuk support

### ISSUE THREAD

**Issue by fsxiyu** [TeamOpenFIRE/OpenFIRE-Firmware#17]
As the title says, with great anticipation.

**Comment by SeongGino** [comment]
I don't really see the desire for this as it would be easier to just use a separate analog stick module and two separate buttons, but we will accept pull requests for someone who wants to add support for Wii Nunchuks.

**Comment by krayon** [comment]
FWIW I would write this however I am now no longer planning on adding the Nunchuck to my guns. In the event I change my mind however I'll certainly get on this if still outstanding.

**Comment by nixxou** [comment]
I still think it's interesting to have the nunchuck option, it's cheap (especially if you already have them), it wont take extra pins (i mean it will just use the same as the display) and you can plug/unplug at will with a convenient i2c plug.
I don't have much use of a jack for pedals on my gun (they works fine as independant devices), so i will just use this space to put a 2ic plug like that.
![image](https://github.com/user-attachments/assets/fbbd0d8a-d885-4e98-9ffc-bc9872a08009)

Anyway, if someone is interested, i went ahead and try to make it work, no idea if it's up to the standard, i just did what i can, so i just leave it here : 
https://github.com/TeamOpenFIRE/OpenFIRE-Firmware/commit/aa4ea6e51df942373c5b7ee693eda432372bb781

The annoying part was, since both run on the same i2c than the display, i had to make something that delay by few ms the nunchuck pull when display->display(); is called. This part is probably perfectible, better use mutex, queue ... But from what i tested, that works well with a display that change an ammo count each 50ms, so good enough for me.
